# For serving site locally
# Note: jekyll-remote-theme has issue with jekyll 4.0.0: https://github.com/benbalter/jekyll-remote-theme/pull/61
#       use jekyll 3.8.6, e.g. 'jekyll _3.8.6_ serve'
plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag

remote_theme: Labs64/NetLicensing-Wiki-template

url: "https://netlicensing.io"
# subpath of the site, e.g. /blog/
baseurl: "/wiki/"

repository: Labs64/wiki

# Enable or disable the site search
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
  "NetLicensing Website":
    - "//netlicensing.io"
  "Management Console":
    - "//ui.netlicensing.io"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2010 <a href=\"https://www.labs64.com\">Labs64 GmbH</a>"
# footer links for the page bottom navigation
footer_links:
  "GuideChimp - Interactive Guided Tours":
    - "https://www.labs64.com/guidechimp/"
  "PluginPass â€“ WordPress License Manager":
    - "https://wordpress.org/plugins/pluginpass-pro-plugintheme-licensing/"

# Google Analytics Tracking
ga_tracking: UA-32654174-2
# ga_tracking: 
ga_tracking_anonymize_ip: true
# Zoho SalesIQ Code
zoho_salesiq_code: "57912641e38953d1e82182c4935dd7cc6768a402d6735d94c891a15169899c4bc025d1c7bcb6f0795fd8083772e86cd8"

# SEO
title: NetLicensing Wiki
description: Resources that will help you learn about Labs64 NetLicensing
logo: "assets/images/logos/netlicensing-logo-transparent.png"
email: info@netlicensing.io
author:
  twitter: netlicensing
twitter:
  username: netlicensing
  card: summary
social:
  name: Labs64 NetLicensing
  links:
    - https://www.linkedin.com/showcase/netlicensing/
    - https://www.xing.com/companies/labs64gmbh
    - https://github.com/Labs64/
    - https://www.facebook.com/netlicensing
    - https://twitter.com/netlicensing
